### ISSUE TITLE
internal server error on register page

### ISSUE THREAD

**Issue by jikang1116** [xosadmin/c5proj#44]
Got internal server error on register page
<img width="1071" alt="Screen Shot 2024-05-04 at 8 24 06 pm" src="https://github.com/xosadmin/c5proj/assets/89113714/06a4eb6e-9631-47e7-b833-5a512405b6bb">

**Comment by jikang1116** [comment]
Now It's fixed!
<img width="1157" alt="Screen Shot 2024-05-04 at 8 33 27 pm" src="https://github.com/xosadmin/c5proj/assets/89113714/feb2ffe2-f1df-41b9-b1ed-927f0bc2ff8b">

**Comment by xosadmin** [comment]
Thanks for point out. Fixed since the commit #1f5b268.
