### ISSUE TITLE
Centralize code for common code.

### ISSUE THREAD

**Issue by Phyo09** [xosadmin/c5proj#51]
We can make navigation bar centralize, meaning no need to repeat navigation html code for every pages. we can use external html embedded within the html pages (e.g., Jinja2)

Pro:
When we make changes, no longer need to update the changes on every html instead do at base.html for common code or duplicated code.

**Comment by Phyo09** [comment]
![image](https://github.com/xosadmin/c5proj/assets/71651933/b84ba069-982e-458d-97bf-190777d57b46)

Below templates are yet to be completed.
* modifycenter (cannot locate)
* accept_request.html
* answerrequest.html
* change_profile.html
* chat_details.html
* confirm_buy.html
* forget_password.html
* index.html (still using?)
* myrequest.html
* newchat.html
* newrequest.html
* newthread.html
* profile_other_user_view.html
* register_complete.html
* requestDetail.html
* search_result.html
* signs.html
* thread_details.html

Done
* chat.html
* community.html
* leaderboard.html
* login.html
* logout.html
* profile.html
* register.html
* requests.html
* shop.html
* todo.html

**Comment by xosadmin** [comment]
There are 2 navigations, depends on user login state. Also, we need to adopt "active" class on specific pages, based on Bootstrap. It is hard to make it centralise.

**Comment by Phyo09** [comment]
There are 2 navigation based on user logged in or not, its centralized, Check again.

**Comment by xosadmin** [comment]
Done
