### ISSUE TITLE
PIN error on Changing Password

### ISSUE THREAD

**Issue by Phyo09** [xosadmin/c5proj#53]
What is the purpose of PIN when changing a password?

I have put the new PIN code but under Profile page, the PIN is not changed. If it's purpose is to check verification, it does not work as well cause, the system allows to change the password with incorrect PIN.

![image](https://github.com/xosadmin/c5proj/assets/71651933/34a59137-3462-4424-9122-06b88405a092)

**Comment by xosadmin** [comment]
PIN is working as 2FA authentication method, which to avoid from unauthorised access and unauthorised password modification

**Comment by xosadmin** [comment]
The mentioned issue has been resolved on the commit #a760446
