### ISSUE TITLE
Forgetpassword is accessible while logged in

### ISSUE THREAD

**Issue by Phyo09** [xosadmin/c5proj#54]
forgetpassword page, 

I am currently logged in but the page is accessible and shown with Home, Login, Sign Up navigation bar (which is for logged out). Can we put current_user.is_authenticated for forgotpassword as well?

**Comment by Phyo09** [comment]
Updated with Jinja2 or base.html for the navigation bar. (See Phyo_branch for demo).

However, current_user.is_authenticated is not implemented yet. Waiting for replies from teammates. 

FYI, it does not make sense for the user to change the password through forget password page. Since the user is logged in, he should change through modify center.

**Comment by xosadmin** [comment]
Fixed on the commit #[16fd472](https://github.com/xosadmin/c5proj/commit/16fd47258b85ebbcf1d46dff519cf3099364deb4)
